# PANDAS AND NUMPY

### NumPy

In [1]:
import pandas as pd
import numpy as np

In [2]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

In [5]:
list3 = list1 + list2
print(list3)

[1, 2, 3, 4, 5, 6]


In [6]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [7]:
array3 = array1 + array2
print(array3)

[5 7 9]


In [9]:
print(array3**(0.5))

array([2.23606798, 2.64575131, 3.        ])

In [11]:
print(array3*2)

[10 14 18]


In [32]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
mat2 = np.array([[0, 2, 1], [-4, 3, 6], [11, -8, 9]])
print(mat2)

[[ 0  2  1]
 [-4  3  6]
 [11 -8  9]]


In [34]:
mat1 * mat2

array([[  0,   4,   3],
       [-16,  15,  36],
       [ 77, -64,  81]])

In [22]:
mat1 + mat2

array([[ 1,  4,  4],
       [ 0,  8, 12],
       [18,  0, 18]])

In [37]:
np.linalg.det(mat1)

-9.51619735392994e-16

### Pandas

In [38]:
import random

In [57]:
# Creating Pandas DataFrame
df1 = pd.DataFrame(np.random.randn(10, 2))
# df1 = pd.DataFrame(np.random.randn(1, 2), columns="hel lo".split(" "))

print(df1)

          0         1
0 -0.902889  0.257783
1 -2.658343 -1.248731
2 -1.155807  0.169837
3  0.887119  0.666756
4 -1.127956  0.056702
5 -0.255806  0.335047
6  0.785274  0.380192
7 -0.378833  0.678101
8 -1.296655 -1.109865
9  1.394854 -0.941573


In [62]:
df1.rename(columns = {0: "col1", 1: "col2"})

,col1,col2
0,-0.902889,0.257783
1,-2.658343,-1.248731
2,-1.155807,0.169837
3,0.887119,0.666756
4,-1.127956,0.056702
5,-0.255806,0.335047
6,0.785274,0.380192
7,-0.378833,0.678101
8,-1.296655,-1.109865
9,1.394854,-0.941573
